#配置端口
server:
  port: 80
  servlet:
    session:
      timeout: 10s

spring:
  thymeleaf:
    cache: false
    enabled: false
  #创建数据库连接
  datasource:
    name: community
    url: jdbc:mysql://43.138.48.181:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

  #创建redis连接
  redis:
    host: 43.138.48.181:3306
    port: 6379

  #设置最大的文件大小和请求大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#关于mybatis相关的配置
mybatis:
  type-aliases-package: com.atlxw.community.entity
  mapperLocations: classpath:mapper/*.xml


#关于日志相关的配置！
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    max-history: 30
    max-size: 10MB
    path: "./logs"
    name: "./logs/mszdqabbs.log"
  level:
    root: INFO